# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "@actions/*"
      octokit:
        patterns:
          - "@octokit/*"
        update-types:
          - "minor"
          - "patch"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
