name: "CodeQL: Combine and post query results"
description: "Combine the results of a batch query run and post to an issue"
author: "GitHub"
runs:
  using: "node12"
  main: "../lib/combine-results.js"
