name: "CodeQL: Query"
description: "Run a CodeQL query against a repository"
author: "GitHub"
inputs:
  controller_repo_id:
    description: "ID of the controller repository where the variant analysis is run."
    required: true

  query_pack_url:
    description: "URL for a tarball containing CodeQL query plus dependencies."
    required: true

  language:
    description: "Language of CodeQL query"
    required: true

  repositories:
    description: "Repositories to run the query against. A JSON encoded array of the form {id: number, nwo: string, token: string}[]"
    required: true

  codeql:
    description: "Path to CodeQL binary to use"
    required: true

  variant_analysis_id:
    description: "The ID of the variant analysis"
    # This will eventually be required once live results is fully rolled out
    # required: true

runs:
  using: "node16"
  main: "../lib/query.js"
