#!/bin/bash

set -eu

cd "$(dirname "$0")/.."

$(npm bin)/ts-json-schema-generator --path ./src/inputs.ts --type RepoArray --out src/json-schemas/RepoArray.json
$(npm bin)/ts-json-schema-generator --path ./src/inputs.ts --type Instructions --out src/json-schemas/Instructions.json
