name: "PR checks"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run-script lint

  check-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Check generated JavaScript
        run: .github/workflows/script/check-js.sh

  check-json-schemas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Check generated JSON schemas
        run: .github/workflows/script/check-json-schemas.sh

  find-deadcode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Find deadcode
        run: npm run find-deadcode

  npm-test:
    needs: [check-js]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: "24.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Initialize CodeQL
        id: init
        uses: github/codeql-action/init@8aad20d150bbac5944a9f9d289da16a4b0d87c1e # v4.36.2
        with:
          languages: javascript

      - name: Put CODEQL on PATH
        run: |
          echo "$(dirname "${{ steps.init.outputs.codeql-path }}")" >> $GITHUB_PATH

      - name: npm run-script test
        run: npm run-script test
