name: "PR checks"

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run-script lint

  check-js:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check generated JavaScript
        run: .github/workflows/script/check-js.sh

  check-json-schemas:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Check generated JSON schemas
        run: .github/workflows/script/check-json-schemas.sh

  find-deadcode:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Find deadcode
        run: npm run find-deadcode

  npm-test:
    needs: [check-js]
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v6
        with:
          node-version: '20.x'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci

      - name: Initialize CodeQL
        id: init
        uses: github/codeql-action/init@v4
        with:
          languages: javascript

      - name: Put CODEQL on PATH
        run: |
          echo "$(dirname "${{ steps.init.outputs.codeql-path }}")" >> $GITHUB_PATH

      - name: npm run-script test
        run: npm run-script test
